# Generated by Django 5.0.4 on 2024-05-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='product_id',
            field=models.JSONField(),
        ),
    ]
