# Generated by Django 5.0.4 on 2024-04-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('category_id', models.IntegerField()),
                ('TGDD_product_link', models.URLField()),
                ('FPT_product_link', models.URLField()),
                ('image', models.URLField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
