# Generated by Django 5.0.4 on 2024-05-10 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.RemoveConstraint(
            model_name='sentiment',
            name='unique_sentiment',
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='company_id',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='blog.company'),
        ),
    ]
